#!/usr/local/bin/perl

use strict;
use warnings;
use Data::Dumper;

my %strsignal = (
    1 => "Hangup",
    2 => "Interrupt",
    3 => "Quit",
    4 => "Illegal instruction",
    5 => "Trace/breakpoint trap",
    6 => "Aborted",
    7 => "Bus error",
    8 => "Floating point exception",
    9 => "Killed",
   11 => "Segmentation fault",
   13 => "Broken pipe",
   14 => "Alarm clock",
   15 => "Terminated",
   16 => "Stack fault",
   17 => "Child exited",
   18 => "Continued",
   19 => "Stopped (signal)",
   20 => "Stopped",
   21 => "Stopped (tty input)",
   22 => "Stopped (tty output)",
   24 => "CPU time limit exceeded",
   25 => "File size limit exceeded",
   26 => "Virtual timer expired",
   27 => "Profiling timer expired",
   28 => "Window changed",
   29 => "I/O possible",
   30 => "Power failure",
   31 => "Bad system call",
);

$0 =~ s|.*/||;
my $makeFile = "Makefile";

my %deps;
my %hashMac;
my %hashDeps;
my %hashCommand;
my @macroArray = ();
my $currTarget;
my @inputs = ();
my @command =();
my $runTarget;
my $argCheck = 0;

if ($ARGV[1]) { $runTarget = $ARGV[1]; $argCheck = 1;}

open my $file, "<$makeFile" or warn "$makeFile: $!\n" and next;
#print "this";
while (<$file>) {
   #print "this ran";
   my $line = $_;
   #chomp $line;
   my $comment = substr($line, 0, 1);
   if ($comment ne "#") {
      #if comment does not contain a tab and contains and equal
      if ($line =~ /=/ && $line !~ /\t/ ) {
         print "= ran";
         push(@macroArray, $line);
      } elsif ($line =~ /:/ && $line !~ /\t/) {
         substr ($line, index($line, ":", 0), 0) = ' ';
         my @words = split m/\s+/, $line;
         $currTarget = $words[0];
         if ($argCheck == 0) {
            $argCheck = 1;
            $runTarget = $currTarget;
         }
#         print "@words \n";
         my %params = map {$_ => 1} @inputs;
         push @inputs, $line;
      } elsif ($line =~ /\t/) {
         $line =~ s/^\t+//;
         my $commandLine = "$currTarget " . "$line";
         push (@command, $commandLine);
         
      }

   }
}
#print "run Target is the following: $runTarget";
#print $runTarget;
#print "array inputs is @inputs";
#print "\n\n\n";
close $file;

sub parse_dep ($) {
   my ($line) = @_;
   return undef unless $line =~ m/^(\S+)\s*:\s*(.*?)\s*$/;
   my ($target ,$dependency) = ($1, ($2));
   my @dependencies = split m/\s+/, $dependency;
   return $target, \@dependencies;
}

for my $macro (@macroArray) {
   my ($mac, $val) = parse_dep $macro;
   print "$0: syntax error: $macro\n" and next unless defined $mac;
   $hashMac{$mac} = $val;
   print "hashMac at $mac is $val";
}



sub parseDependencies($) {
   my($line) = @_;
   return undef unless $line =~ m/^(\S+)\s*:\s*(.*?)\s*$/;
   my ($target, $dependency) = ($1, ($2));
   my @dependencies = split m/\s+/, $dependency;
   return $target, \@dependencies;

}

for my $input (@inputs) {
#   print "input for each inputs is $input";
   my ($target, $depen) = parseDependencies $input;
   print"$0: syntax error: $input\n" and next unless defined $target;
   $hashDeps{$target} = $depen;
   #print Dumper(\%hashDeps);
}
#print "command is @command";
for my $commands (@command) {
   my @pushcommand = ();
   my $realCommand = "";
   my $tgt = substr ($commands, 0 , index ($commands, ' '));
   my $cmds = substr ($commands, index ($commands, ' ') + 1);
   #print "tgt is $tgt and cmds is $cmds";
   my @commandWord = split m/\s+/, $cmds;
   foreach(@commandWord) {
      $realCommand = "$realCommand" . "$_ ";
   }
   $realCommand =~ s/\s+$//;
   push @pushcommand, $realCommand;
  # print $realCommand;
   $hashCommand{$tgt} = \@pushcommand;
}   
#print Dumper(\%hashCommand);

sub runCommands ($) {

   my ($target) = @_;
   my $runCommand = %$hashCommand{$target};
   my @dependents = ($hashDeps{$target});

   print $runCommand;
}

print Dumper(\%hashCommand);
print Dumper(\%hashDeps);
runCommands($runTarget);
